-- Analysis Phase. 


-- ---------------- 

-- (Q1.) Number of brands in the segment.

SELECT 
   COUNT(DISTINCT ï»¿BrandName) AS NumberOfBrands
FROM 
   `scrapping data`.smart_lock;
-- --------------------------------------------
--  (Q2.) Count of SKUs per brand.

SELECT 
   ï»¿BrandName AS BrandName, 
   COUNT(*) AS SKUCount
FROM 
   `scrapping data`.smart_lock
GROUP BY 
   1;
--------------------------------------------------
-- (Q3.) Relative ranking: Create a formula to rank brands based on the rank of the SKUs in the 
--       search results. E.g.: Brand A has 4 SKUs in the search results and Brand B has 6 SKUs in 
--       the search results.
SELECT
IFNULL(CASE WHEN ï»¿BrandName = 'IFITech' THEN Title END, ' ') AS IFITech_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'IFITech' THEN Ranking END, ' ') AS IFITech_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Atomberg' THEN Title END, ' ') AS Atomberg_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Atomberg' THEN Ranking END, ' ') AS Atomberg_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'PalD' THEN Title END, ' ') AS PalD_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'PalD' THEN Ranking END, ' ') AS PalD_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Kesig' THEN Title END, ' ') AS Kesig_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Kesig' THEN Ranking END, ' ') AS Kesig_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'ZODIAQUE' THEN Title END, ' ') AS ZODIAQUE_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'ZODIAQUE' THEN Ranking END, ' ') AS ZODIAQUE_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'DPS' THEN Title END, ' ') AS DPS_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'DPS' THEN Ranking END, ' ') AS DPS_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'DANDH' THEN Title END, ' ') AS DANDH_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'DANDH' THEN Ranking END, ' ') AS DANDH_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'DEZIINE' THEN Title END, ' ') AS DEZIINE_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'DEZIINE' THEN Ranking END, ' ') AS DEZIINE_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'TYAG' THEN Title END, ' ') AS TYAG_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'TYAG' THEN Ranking END, ' ') AS TYAG_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'PROBEROS' THEN Title END, ' ') AS PROBEROS_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'PROBEROS' THEN Ranking END, ' ') AS PROBEROS_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'MANTAVYA' THEN Title END, ' ') AS MANTAVYA_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'MANTAVYA' THEN Ranking END, ' ') AS MANTAVYA_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'hazon' THEN Title END, ' ') AS hazon_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'hazon' THEN Ranking END, ' ') AS hazon_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'SKYZONE' THEN Title END, ' ') AS SKYZONE_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'SKYZONE' THEN Ranking END, ' ') AS SKYZONE_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Godrej' THEN Title END, ' ') AS Godrej_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Godrej' THEN Ranking END, ' ') AS Godrej_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Luxafare' THEN Title END, ' ') AS Luxafare_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Luxafare' THEN Ranking END, ' ') AS Luxafare_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'AltroSmart' THEN Title END, ' ') AS AltroSmart_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'AltroSmart' THEN Ranking END, ' ') AS AltroSmart_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'oob' THEN Title END, ' ') AS oob_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'oob' THEN Ranking END, ' ') AS oob_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'AMT' THEN Title END, ' ') AS AMT_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'AMT' THEN Ranking END, ' ') AS AMT_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Phlipton' THEN Title END, ' ') AS Phlipton_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Phlipton' THEN Ranking END, ' ') AS Phlipton_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'boltinnovations' THEN Title END, ' ') AS boltinnovations_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'boltinnovations' THEN Ranking END, ' ') AS boltinnovations_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Akhand' THEN Title END, ' ') AS Akhand_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Akhand' THEN Ranking END, ' ') AS Akhand_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Targus' THEN Title END, ' ') AS Targus_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Targus' THEN Ranking END, ' ') AS Targus_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'ZKTeco' THEN Title END, ' ') AS ZKTeco_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'ZKTeco' THEN Ranking END, ' ') AS ZKTeco_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'SPEEDY' THEN Title END, ' ') AS SPEEDY_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'SPEEDY' THEN Ranking END, ' ') AS SPEEDY_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'SECUREYE' THEN Title END, ' ') AS SECUREYE_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'SECUREYE' THEN Ranking END, ' ') AS SECUREYE_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'jenix' THEN Title END, ' ') AS jenix_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'jenix' THEN Ranking END, ' ') AS jenix_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'CRAZYGOL' THEN Title END, ' ') AS CRAZYGOL_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'CRAZYGOL' THEN Ranking END, ' ') AS CRAZYGOL_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'OZONE' THEN Title END, ' ') AS OZONE_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'OZONE' THEN Ranking END, ' ') AS OZONE_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'IIVAAs' THEN Title END, ' ') AS IIVAAs_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'IIVAAs' THEN Ranking END, ' ') AS IIVAAs_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'iSmart' THEN Title END, ' ') AS iSmart_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'iSmart' THEN Ranking END, ' ') AS iSmart_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'VALENCIA' THEN Title END, ' ') AS VALENCIA_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'VALENCIA' THEN Ranking END, ' ') AS VALENCIA_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Qubo' THEN Title END, ' ') AS Qubo_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Qubo' THEN Ranking END, ' ') AS Qubo_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'eSSL' THEN Title END, ' ') AS eSSL_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'eSSL' THEN Ranking END, ' ') AS eSSL_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'MARS' THEN Title END, ' ') AS MARS_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'MARS' THEN Ranking END, ' ') AS MARS_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'HomeMate' THEN Title END, ' ') AS HomeMate_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'HomeMate' THEN Ranking END, ' ') AS HomeMate_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Technik' THEN Title END, ' ') AS Technik_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Technik' THEN Ranking END, ' ') AS Technik_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'azLock' THEN Title END, ' ') AS azLock_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'azLock' THEN Ranking END, ' ') AS azLock_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Nexmot' THEN Title END, ' ') AS Nexmot_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Nexmot' THEN Ranking END, ' ') AS Nexmot_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'BonKaso' THEN Title END, ' ') AS BonKaso_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'BonKaso' THEN Ranking END, ' ') AS BonKaso_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Aayansh' THEN Title END, ' ') AS Aayansh_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Aayansh' THEN Ranking END, ' ') AS Aayansh_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'SSVL' THEN Title END, ' ') AS SSVL_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'SSVL' THEN Ranking END, ' ') AS SSVL_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'tuchware' THEN Title END, ' ') AS tuchware_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'tuchware' THEN Ranking END, ' ') AS tuchware_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'PLUS' THEN Title END, ' ') AS PLUS_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'PLUS' THEN Ranking END, ' ') AS PLUS_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Pooja' THEN Title END, ' ') AS Pooja_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Pooja' THEN Ranking END, ' ') AS Pooja_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'amiciSmart' THEN Title END, ' ') AS amiciSmart_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'amiciSmart' THEN Ranking END, ' ') AS amiciSmart_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Bush' THEN Title END, ' ') AS Bush_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Bush' THEN Ranking END, ' ') AS Bush_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Yele' THEN Title END, ' ') AS Yele_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Yele' THEN Ranking END, ' ') AS Yele_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Yabby' THEN Title END, ' ') AS Yabby_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Yabby' THEN Ranking END, ' ') AS Yabby_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'omismartlock' THEN Title END, ' ') AS omismartlock_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'omismartlock' THEN Ranking END, ' ') AS omismartlock_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'YogpriDeal' THEN Title END, ' ') AS YogpriDeal_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'YogpriDeal' THEN Ranking END, ' ') AS YogpriDeal_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'GOLENS' THEN Title END, ' ') AS GOLENS_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'GOLENS' THEN Ranking END, ' ') AS GOLENS_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'ABEZBeSmart' THEN Title END, ' ') AS ABEZBeSmart_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'ABEZBeSmart' THEN Ranking END, ' ') AS ABEZBeSmart_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Yale' THEN Title END, ' ') AS Yale_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Yale' THEN Ranking END, ' ') AS Yale_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'iPlug' THEN Title END, ' ') AS iPlug_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'iPlug' THEN Ranking END, ' ') AS iPlug_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Retekess' THEN Title END, ' ') AS Retekess_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Retekess' THEN Ranking END, ' ') AS Retekess_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'audiovan' THEN Title END, ' ') AS audiovan_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'audiovan' THEN Ranking END, ' ') AS audiovan_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Robsync' THEN Title END, ' ') AS Robsync_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Robsync' THEN Ranking END, ' ') AS Robsync_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Denler' THEN Title END, ' ') AS Denler_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Denler' THEN Ranking END, ' ') AS Denler_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'ABEZ' THEN Title END, ' ') AS ABEZ_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'ABEZ' THEN Ranking END, ' ') AS ABEZ_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'TECHGEAR' THEN Title END, ' ') AS TECHGEAR_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'TECHGEAR' THEN Ranking END, ' ') AS TECHGEAR_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'primepick' THEN Title END, ' ') AS primepick_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'primepick' THEN Ranking END, ' ') AS primepick_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'ismart' THEN Title END, ' ') AS ismart_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'ismart' THEN Ranking END, ' ') AS ismart_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'iCare' THEN Title END, ' ') AS iCare_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'iCare' THEN Ranking END, ' ') AS iCare_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'HAVTON' THEN Title END, ' ') AS HAVTON_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'HAVTON' THEN Ranking END, ' ') AS HAVTON_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Breewell' THEN Title END, ' ') AS Breewell_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Breewell' THEN Ranking END, ' ') AS Breewell_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'LOCKOMATIC' THEN Title END, ' ') AS LOCKOMATIC_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'LOCKOMATIC' THEN Ranking END, ' ') AS LOCKOMATIC_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'RS' THEN Title END, ' ') AS RS_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'RS' THEN Ranking END, ' ') AS RS_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'SMARTLOCK' THEN Title END, ' ') AS SMARTLOCK_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'SMARTLOCK' THEN Ranking END, ' ') AS SMARTLOCK_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Smartfive' THEN Title END, ' ') AS Smartfive_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Smartfive' THEN Ranking END, ' ') AS Smartfive_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'mariya' THEN Title END, ' ') AS mariya_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'mariya' THEN Ranking END, ' ') AS mariya_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'SLYDER' THEN Title END, ' ') AS SLYDER_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'SLYDER' THEN Ranking END, ' ') AS SLYDER_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Prosafe' THEN Title END, ' ') AS Prosafe_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Prosafe' THEN Ranking END, ' ') AS Prosafe_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'MRPlaywood' THEN Title END, ' ') AS MRPlaywood_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'MRPlaywood' THEN Ranking END, ' ') AS MRPlaywood_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Worksaat' THEN Title END, ' ') AS Worksaat_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Worksaat' THEN Ranking END, ' ') AS Worksaat_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'HAWK' THEN Title END, ' ') AS HAWK_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'HAWK' THEN Ranking END, ' ') AS HAWK_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'SOLITY' THEN Title END, ' ') AS SOLITY_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'SOLITY' THEN Ranking END, ' ') AS SOLITY_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Rhonnium' THEN Title END, ' ') AS Rhonnium_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Rhonnium' THEN Ranking END, ' ') AS Rhonnium_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'DHARAM' THEN Title END, ' ') AS DHARAM_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'DHARAM' THEN Ranking END, ' ') AS DHARAM_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Tekninja' THEN Title END, ' ') AS Tekninja_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Tekninja' THEN Ranking END, ' ') AS Tekninja_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'DWIJA' THEN Title END, ' ') AS DWIJA_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'DWIJA' THEN Ranking END, ' ') AS DWIJA_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Microleaf' THEN Title END, ' ') AS Microleaf_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Microleaf' THEN Ranking END, ' ') AS Microleaf_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'FORT' THEN Title END, ' ') AS FORT_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'FORT' THEN Ranking END, ' ') AS FORT_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Phamvio' THEN Title END, ' ') AS Phamvio_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Phamvio' THEN Ranking END, ' ') AS Phamvio_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'V' THEN Title END, ' ') AS V_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'V' THEN Ranking END, ' ') AS V_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Zunpulse' THEN Title END, ' ') AS Zunpulse_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Zunpulse' THEN Ranking END, ' ') AS Zunpulse_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Hawkvision' THEN Title END, ' ') AS Hawkvision_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Hawkvision' THEN Ranking END, ' ') AS Hawkvision_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = "Safe'O'Buddy" THEN Title END, ' ') AS Safe_O_Buddy_Title,
IFNULL(CASE WHEN ï»¿BrandName = "Safe'O'Buddy" THEN Ranking END, ' ') AS Safe_O_Buddy_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Meguard' THEN Title END, ' ') AS Meguard_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Meguard' THEN Ranking END, ' ') AS Meguard_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'ALLY' THEN Title END, ' ') AS ALLY_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'ALLY' THEN Ranking END, ' ') AS ALLY_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Prabhu' THEN Title END, ' ') AS Prabhu_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Prabhu' THEN Ranking END, ' ') AS Prabhu_Ranking,
IFNULL(CASE WHEN ï»¿BrandName = 'Elevea' THEN Title END, ' ') AS Elevea_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Elevea' THEN Ranking END, ' ') AS Elevea_Ranking
FROM `scrapping data`.smart_lock;




-------------------------------------------------------

-- (Q4.) Relative rating.

SELECT
IFNULL(CASE WHEN ï»¿BrandName = 'Yale' THEN Title END, ' ') AS Yale_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Yale' THEN Rating END, ' ') AS Yale_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'amiciSmart' THEN Title END, ' ') AS amiciSmart_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'amiciSmart' THEN Rating END, ' ') AS amiciSmart_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Atomberg' THEN Title END, ' ') AS Atomberg_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Atomberg' THEN Rating END, ' ') AS Atomberg_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Breewell' THEN Title END, ' ') AS Breewell_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Breewell' THEN Rating END, ' ') AS Breewell_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Kesig' THEN Title END, ' ') AS Kesig_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Kesig' THEN Rating END, ' ') AS Kesig_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'VALENCIA' THEN Title END, ' ') AS VALENCIA_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'VALENCIA' THEN Rating END, ' ') AS VALENCIA_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Qubo' THEN Title END, ' ') AS Qubo_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Qubo' THEN Rating END, ' ') AS Qubo_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Godrej' THEN Title END, ' ') AS Godrej_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Godrej' THEN Rating END, ' ') AS Godrej_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'IFITech' THEN Title END, ' ') AS IFITech_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'IFITech' THEN Rating END, ' ') AS IFITech_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'ZODIAQUE' THEN Title END, ' ') AS ZODIAQUE_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'ZODIAQUE' THEN Rating END, ' ') AS ZODIAQUE_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'DANDH' THEN Title END, ' ') AS DANDH_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'DANDH' THEN Rating END, ' ') AS DANDH_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'TYAG' THEN Title END, ' ') AS TYAG_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'TYAG' THEN Rating END, ' ') AS TYAG_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'DEZIINE' THEN Title END, ' ') AS DEZIINE_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'DEZIINE' THEN Rating END, ' ') AS DEZIINE_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Robsync' THEN Title END, ' ') AS Robsync_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Robsync' THEN Rating END, ' ') AS Robsync_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'azLock' THEN Title END, ' ') AS azLock_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'azLock' THEN Rating END, ' ') AS azLock_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'DWIJA' THEN Title END, ' ') AS DWIJA_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'DWIJA' THEN Rating END, ' ') AS DWIJA_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'YogpriDeal' THEN Title END, ' ') AS YogpriDeal_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'YogpriDeal' THEN Rating END, ' ') AS YogpriDeal_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Luxafare' THEN Title END, ' ') AS Luxafare_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Luxafare' THEN Rating END, ' ') AS Luxafare_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'SPEEDY' THEN Title END, ' ') AS SPEEDY_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'SPEEDY' THEN Rating END, ' ') AS SPEEDY_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'MANTAVYA' THEN Title END, ' ') AS MANTAVYA_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'MANTAVYA' THEN Rating END, ' ') AS MANTAVYA_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'CRAZYGOL' THEN Title END, ' ') AS CRAZYGOL_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'CRAZYGOL' THEN Rating END, ' ') AS CRAZYGOL_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'SKYZONE' THEN Title END, ' ') AS SKYZONE_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'SKYZONE' THEN Rating END, ' ') AS SKYZONE_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'AMT' THEN Title END, ' ') AS AMT_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'AMT' THEN Rating END, ' ') AS AMT_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Aayansh' THEN Title END, ' ') AS Aayansh_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Aayansh' THEN Rating END, ' ') AS Aayansh_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'ABEZ' THEN Title END, ' ') AS ABEZ_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'ABEZ' THEN Rating END, ' ') AS ABEZ_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'ABEZBeSmart' THEN Title END, ' ') AS ABEZBeSmart_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'ABEZBeSmart' THEN Rating END, ' ') AS ABEZBeSmart_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'ALLY' THEN Title END, ' ') AS ALLY_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'ALLY' THEN Rating END, ' ') AS ALLY_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Akhand' THEN Title END, ' ') AS Akhand_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Akhand' THEN Rating END, ' ') AS Akhand_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'AltroSmart' THEN Title END, ' ') AS AltroSmart_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'AltroSmart' THEN Rating END, ' ') AS AltroSmart_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'BonKaso' THEN Title END, ' ') AS BonKaso_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'BonKaso' THEN Rating END, ' ') AS BonKaso_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Bush' THEN Title END, ' ') AS Bush_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Bush' THEN Rating END, ' ') AS Bush_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'DHARAM' THEN Title END, ' ') AS DHARAM_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'DHARAM' THEN Rating END, ' ') AS DHARAM_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'DPS' THEN Title END, ' ') AS DPS_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'DPS' THEN Rating END, ' ') AS DPS_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Denler' THEN Title END, ' ') AS Denler_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Denler' THEN Rating END, ' ') AS Denler_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Elevea' THEN Title END, ' ') AS Elevea_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Elevea' THEN Rating END, ' ') AS Elevea_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'FORT' THEN Title END, ' ') AS FORT_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'FORT' THEN Rating END, ' ') AS FORT_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'GOLENS' THEN Title END, ' ') AS GOLENS_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'GOLENS' THEN Rating END, ' ') AS GOLENS_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'HAVTON' THEN Title END, ' ') AS HAVTON_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'HAVTON' THEN Rating END, ' ') AS HAVTON_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'HAWK' THEN Title END, ' ') AS HAWK_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'HAWK' THEN Rating END, ' ') AS HAWK_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Hawkvision' THEN Title END, ' ') AS Hawkvision_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Hawkvision' THEN Rating END, ' ') AS Hawkvision_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'HomeMate' THEN Title END, ' ') AS HomeMate_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'HomeMate' THEN Rating END, ' ') AS HomeMate_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'IIVAAs' THEN Title END, ' ') AS IIVAAs_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'IIVAAs' THEN Rating END, ' ') AS IIVAAs_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'LOCKOMATIC' THEN Title END, ' ') AS LOCKOMATIC_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'LOCKOMATIC' THEN Rating END, ' ') AS LOCKOMATIC_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'MARS' THEN Title END, ' ') AS MARS_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'MARS' THEN Rating END, ' ') AS MARS_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'MRPlaywood' THEN Title END, ' ') AS MRPlaywood_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'MRPlaywood' THEN Rating END, ' ') AS MRPlaywood_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Meguard' THEN Title END, ' ') AS Meguard_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Meguard' THEN Rating END, ' ') AS Meguard_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Microleaf' THEN Title END, ' ') AS Microleaf_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Microleaf' THEN Rating END, ' ') AS Microleaf_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Nexmot' THEN Title END, ' ') AS Nexmot_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Nexmot' THEN Rating END, ' ') AS Nexmot_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'OZONE' THEN Title END, ' ') AS OZONE_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'OZONE' THEN Rating END, ' ') AS OZONE_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'PLUS' THEN Title END, ' ') AS PLUS_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'PLUS' THEN Rating END, ' ') AS PLUS_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'PROBEROS' THEN Title END, ' ') AS PROBEROS_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'PROBEROS' THEN Rating END, ' ') AS PROBEROS_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'PalD' THEN Title END, ' ') AS PalD_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'PalD' THEN Rating END, ' ') AS PalD_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Phamvio' THEN Title END, ' ') AS Phamvio_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Phamvio' THEN Rating END, ' ') AS Phamvio_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Phlipton' THEN Title END, ' ') AS Phlipton_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Phlipton' THEN Rating END, ' ') AS Phlipton_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Pooja' THEN Title END, ' ') AS Pooja_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Pooja' THEN Rating END, ' ') AS Pooja_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Prabhu' THEN Title END, ' ') AS Prabhu_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Prabhu' THEN Rating END, ' ') AS Prabhu_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Prosafe' THEN Title END, ' ') AS Prosafe_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Prosafe' THEN Rating END, ' ') AS Prosafe_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'RS' THEN Title END, ' ') AS RS_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'RS' THEN Rating END, ' ') AS RS_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Retekess' THEN Title END, ' ') AS Retekess_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Retekess' THEN Rating END, ' ') AS Retekess_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Rhonnium' THEN Title END, ' ') AS Rhonnium_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Rhonnium' THEN Rating END, ' ') AS Rhonnium_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'SECUREYE' THEN Title END, ' ') AS SECUREYE_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'SECUREYE' THEN Rating END, ' ') AS SECUREYE_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'SLYDER' THEN Title END, ' ') AS SLYDER_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'SLYDER' THEN Rating END, ' ') AS SLYDER_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'SMARTLOCK' THEN Title END, ' ') AS SMARTLOCK_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'SMARTLOCK' THEN Rating END, ' ') AS SMARTLOCK_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'SOLITY' THEN Title END, ' ') AS SOLITY_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'SOLITY' THEN Rating END, ' ') AS SOLITY_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'SSVL' THEN Title END, ' ') AS SSVL_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'SSVL' THEN Rating END, ' ') AS SSVL_Rating,
IFNULL(CASE WHEN ï»¿BrandName = "Safe'O'Buddy" THEN Title END, ' ') AS Safe_O_Buddy_Title,
IFNULL(CASE WHEN ï»¿BrandName = "Safe'O'Buddy" THEN Rating END, ' ') AS Safe_O_Buddy_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Smartfive' THEN Title END, ' ') AS Smartfive_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Smartfive' THEN Rating END, ' ') AS Smartfive_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'TECHGEAR' THEN Title END, ' ') AS TECHGEAR_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'TECHGEAR' THEN Rating END, ' ') AS TECHGEAR_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Targus' THEN Title END, ' ') AS Targus_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Targus' THEN Rating END, ' ') AS Targus_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Technik' THEN Title END, ' ') AS Technik_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Technik' THEN Rating END, ' ') AS Technik_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Tekninja' THEN Title END, ' ') AS Tekninja_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Tekninja' THEN Rating END, ' ') AS Tekninja_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'V' THEN Title END, ' ') AS V_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'V' THEN Rating END, ' ') AS V_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Worksaat' THEN Title END, ' ') AS Worksaat_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Worksaat' THEN Rating END, ' ') AS Worksaat_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Yabby' THEN Title END, ' ') AS Yabby_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Yabby' THEN Rating END, ' ') AS Yabby_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Yele' THEN Title END, ' ') AS Yele_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Yele' THEN Rating END, ' ') AS Yele_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'ZKTeco' THEN Title END, ' ') AS ZKTeco_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'ZKTeco' THEN Rating END, ' ') AS ZKTeco_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'Zunpulse' THEN Title END, ' ') AS Zunpulse_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'Zunpulse' THEN Rating END, ' ') AS Zunpulse_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'audiovan' THEN Title END, ' ') AS audiovan_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'audiovan' THEN Rating END, ' ') AS audiovan_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'boltinnovations' THEN Title END, ' ') AS boltinnovations_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'boltinnovations' THEN Rating END, ' ') AS boltinnovations_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'eSSL' THEN Title END, ' ') AS eSSL_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'eSSL' THEN Rating END, ' ') AS eSSL_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'hazon' THEN Title END, ' ') AS hazon_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'hazon' THEN Rating END, ' ') AS hazon_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'iCare' THEN Title END, ' ') AS iCare_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'iCare' THEN Rating END, ' ') AS iCare_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'iPlug' THEN Title END, ' ') AS iPlug_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'iPlug' THEN Rating END, ' ') AS iPlug_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'iSmart' THEN Title END, ' ') AS iSmart_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'iSmart' THEN Rating END, ' ') AS iSmart_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'ismart' THEN Title END, ' ') AS ismart_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'ismart' THEN Rating END, ' ') AS ismart_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'jenix' THEN Title END, ' ') AS jenix_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'jenix' THEN Rating END, ' ') AS jenix_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'mariya' THEN Title END, ' ') AS mariya_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'mariya' THEN Rating END, ' ') AS mariya_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'omismartlock' THEN Title END, ' ') AS omismartlock_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'omismartlock' THEN Rating END, ' ') AS omismartlock_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'oob' THEN Title END, ' ') AS oob_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'oob' THEN Rating END, ' ') AS oob_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'primepick' THEN Title END, ' ') AS primepick_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'primepick' THEN Rating END, ' ') AS primepick_Rating,
IFNULL(CASE WHEN ï»¿BrandName = 'tuchware' THEN Title END, ' ') AS tuchware_Title,
IFNULL(CASE WHEN ï»¿BrandName = 'tuchware' THEN Rating END, ' ') AS tuchware_Rating
FROM `scrapping data`.smart_lock;


---------------------------------------------

-- (Q5.) Price distribution of SKUs


SELECT
    CASE
        WHEN Price < 4999 THEN '<INR 4999'
        WHEN Price BETWEEN 3000 AND 4999 THEN 'INR 3000-4999'
        WHEN Price BETWEEN 5000 AND 9999 THEN 'INR 5000-9999'
        WHEN Price BETWEEN 10000 AND 14999 THEN 'INR 10000-14999'
        WHEN Price BETWEEN 15000 AND 19999 THEN 'INR 15000-19999'
        ELSE 'Greater than 20000'
    END AS PriceBand,
    COUNT(*) AS SKUCount
FROM  `scrapping data`.smart_lock
GROUP BY PriceBand

